CREATE TABLE TICKER (
    symbol VARCHAR(255) NOT NULL,
    service VARCHAR(255) NOT NULL,
    bidPrice DECIMAL(20, 8) NOT NULL,
    bidQuantity DECIMAL(20, 8) NOT NULL,
    askPrice DECIMAL(20, 8) NOT NULL,
    askQuantity DECIMAL(20, 8) NOT NULL,
    PRIMARY KEY (symbol, service)
);

CREATE TABLE CRYPTO_USER (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    walletBalance DECIMAL(20, 8) NOT NULL
);

CREATE TABLE TRADE (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    SYMBOL VARCHAR(255) NOT NULL,
    QUANTITY DECIMAL(19, 4) NOT NULL,
    PRICE DECIMAL(19, 4) NOT NULL,
    IS_BUY_ORDER BOOLEAN NOT NULL,
    TRADE_TIMESTAMP TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES CRYPTO_USER(ID)
);
