CREATE TABLE TICKER (
    symbol VARCHAR(255) NOT NULL,
    service VARCHAR(255) NOT NULL,
    bidPrice DECIMAL(20, 8),
    bidQuantity DECIMAL(20, 8),
    askPrice DECIMAL(20, 8),
    askQuantity DECIMAL(20, 8),
    PRIMARY KEY (symbol, service)
);

CREATE TABLE USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    WALLET_BALANCE DECIMAL(19, 4) NOT NULL
);

CREATE TABLE TRADE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SYMBOL VARCHAR(255) NOT NULL,
    QUANTITY DECIMAL(19, 4) NOT NULL,
    PRICE DECIMAL(19, 4) NOT NULL,
    IS_BUY_ORDER BOOLEAN NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
