CREATE TABLE TICKER (
    symbol VARCHAR(255) NOT NULL,
    service VARCHAR(255) NOT NULL,
    bidPrice DECIMAL(20, 8) NOT NULL,
    bidQuantity DECIMAL(20, 8) NOT NULL,
    askPrice DECIMAL(20, 8) NOT NULL,
    askQuantity DECIMAL(20, 8) NOT NULL,
    PRIMARY KEY (symbol, service)
);

CREATE TABLE CRYPTO_USER (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TRADE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    quantity DECIMAL(20, 8) NOT NULL,
    price DECIMAL(20, 8) NOT NULL,
    isBuyOrder BOOLEAN NOT NULL,
    tradeTimestamp TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES CRYPTO_USER(id)
);

CREATE TABLE WALLET (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    cashBalance DECIMAL(20, 8) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES CRYPTO_USER(id)
);

CREATE TABLE WALLET_ITEM (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    quantity DECIMAL(20, 8) NOT NULL,
    wallet_id INTEGER NOT NULL,
    FOREIGN KEY (wallet_id) REFERENCES WALLET(id)
);
